services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sodam
      MYSQL_USER: sodam
      MYSQL_PASSWORD: 4444
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  fastapi:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: jenkins
    restart: always
volumes:
  db_data:
  jenkins_home: